### ISSUE TITLE
MOTD Display Issues

### ISSUE THREAD

**Issue by madeofstown** [Rjlintkh/bdsx-web-panel#2]
Web-panel version: Latest version on github as of December 5, 2021
BDSX Version: cloned from github December 5, 2021

The MOTD display seems to have an issue with dynamic (changing) MOTD. 

![motdbug](https://user-images.githubusercontent.com/33820964/144863549-402f1ae4-1425-4f45-b6f5-1e94c3281cb2.png)

**Comment by Rjlintkh** [comment]
Just pushed a fix to it, thanks for ur report!
